# Service-specific configuration for Gagarin
image:
  repository: "ghcr.io/fyodorovai/gagarin"
  tag: "main"

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 500Mi

# Enable ingress with service-specific host
ingress:
  enabled: true
  hosts:
    - gagarin.danielransom.com

# Environment variables specific to Gagarin
env: {}