replicaCount: 1

image:
  repository: ghcr.io/fyodorovai/gagarin
  tag: main
  pullPolicy: Always

service:
  type: ClusterIP
  ports: 
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 500Mi

ingress:
  enabled: true
  hosts:
    - gagarin.danielransom.com
  tls: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: supabaseProjectURL
    value: ""
  - name: supabaseAPIKey
    value: ""
  - name: jwtSecret
    value: ""